sudo: required
services:
  - docker

#before_install 

script: 'true'

after_success:
  - docker build -t "$DOCKER_USERNAME"/node-project:$(git log -1 --format=%h) .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  - docker tag "$DOCKER_USERNAME"/node-project:$(git log -1 --format=%h) "$DOCKER_USERNAME"/node-project:latest

  - docker push "$DOCKER_USERNAME"/node-project