sudo: required
services:
  - docker

#before_install 

script: 'true'

env:
  - TAG=development # must development for development branch


after_success:
  

  - docker build -t "$DOCKER_USERNAME"/node-project:$TAG .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  - docker tag "$DOCKER_USERNAME"/node-project:$TAG "$DOCKER_USERNAME"/node-project:latest

  - docker push "$DOCKER_USERNAME"/node-project

# Deploy to EBS
deploy:
  - provider: elasticbeanstalk
    region: "us-east-1"
    app: "travis-testing"
    env: "TravisTesting-env"
    bucket_name: "elasticbeanstalk-us-east-1-264795727753"
    bucket_path: "TravisTesting-env"
    on:
      branch: master
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"