sudo: required
services:
  - docker

#before_install 

script: 'true'

env:
  - TAG=development # must development for development branch

after_success:
  - docker build -t "$DOCKER_USERNAME"/node-project:$TAG .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  - docker tag "$DOCKER_USERNAME"/node-project:$TAG "$DOCKER_USERNAME"/node-project:latest

  - docker push "$DOCKER_USERNAME"/node-project